### ISSUE TITLE
field restriction using some weird wildcard from the subject

### ISSUE THREAD

**Issue by maxadamo** [slash2009/XWMM#123]
I am going to explain, as the subject is not understandable :) 
In italian I do have the movie genres: "azione", "animazione" (they are "action", "animation").
In this case "azione" also includes all movies from "animazione" :)

**Comment by fyfe** [comment]
[resources/js/app/movies/moviegenre.js Line 102](https://github.com/slash2009/XWMM/blob/c7c2d9ce25bf0cdf91efdc9ed7c6675db110ed1e/resources/js/app/movies/moviegenre.js#L102) operator needs changed from "contains" to "is"

The same is probably true of [resources/js/app/movies/movieset.js Line 75](https://github.com/slash2009/XWMM/blob/c7c2d9ce25bf0cdf91efdc9ed7c6675db110ed1e/resources/js/app/movies/movieset.js#L75) and [resources/js/app/common/genre.js Line 90](https://github.com/slash2009/XWMM/blob/c7c2d9ce25bf0cdf91efdc9ed7c6675db110ed1e/resources/js/app/common/genre.js#L90).

I'm away until the 25th and can't fix this any sooner (don't have my laptop with me).

**Comment by uNiversaI** [comment]
@fyfe please see #124 its your button for the merge I can update the release accordingly
