### ISSUE TITLE
Display file location

### ISSUE THREAD

**Issue by snakyjake1** [slash2009/XWMM#126]
I would like to see the file location (and a link to the folder of the file).

Example:
When viewing the metadata of a movie or TV show, I can see the information for Title, Genre, etc...but there is no information regarding the location of the file.

I desperately need to know the full path location and file name of the movie/show/music.

Thanks,
Jake

**Comment by fyfe** [comment]
![image](https://cloud.githubusercontent.com/assets/1221156/6179279/75981c96-b30f-11e4-8bae-30fe0a37bf82.png)
1. open the right panel (I might revert c869d1a29ef5abe40a1b7ed795a5757751c32b63 and have it open by default)
2. select `Other Details`
3. file location

**Comment by snakyjake1** [comment]
Thanks!

**Comment by uNiversaI** [comment]
My 2c, I think it should be open by default or should be more obvious its collapsed, someone in forums had already found this new handling awkward.
