### ISSUE TITLE
Remove version from addon directory name

### ISSUE THREAD

**Issue by PopovK** [slash2009/XWMM#129]
It would be helpfull to remove the version from the WIMM directory name in the addon directory  

As example, my current .kodi/addon dir contains the following : 
> ls -1|grep WIMM 
webinterface.WIMM-4.1.14
webinterface.WIMM-4.1.15
webinterface.WIMM-4.1.16

Not the first time I've done some cleaning with VIMM versions. 

It also create a conflict with a multiple web interface installation : I created a symlink under webinterface.default to addons/WIMM, and while it's working as expected, WIMM updates aren't usable unless the symlink is also updated. Manually, of course.

Dunno if there's currently a use for keeping the multiples versions in the dir name, but from what I saw, VIMM is the only one using the version number in his own directory name

Thanks

**Comment by uNiversaI** [comment]
There's no use I can think of, this is probably a result of the zipping both via git source and by zipping up the addon for distribution.

I dont understand how having this version affects the operation of the addon, or how it interferes with multiple web interface installs, you cant install multiple versions of WIMM onto same Kodi version without modifying the addon ID in addon.xml.

This isnt a bug an Ill wait for @fyfe to chyme in, so for now Ill mark this as a feature request.

BTW its WIMM not VIMM :smile:

**Comment by fyfe** [comment]
Yes I noticed this a while back when I setup the update repository and I forgot to fix it. I've updated the repo update script and tagged a new release. So from v4.1.17 the version number won't be tacked on the end of the folder name.

@PopovK on a side note do you know you can access all the installed web interfaces from http://[ip address]/addons/ there's no need to create a symlink inside webinterface.default.

**Comment by PopovK** [comment]
Just for the record, the version number doesn't prevent the addon to work, but if using a symlink, as it target a specific directory, when a new version come in you will still use the previous one.
Dunno if it's clear, maybe like this : 

current version : 
kodi/addon
	webinterface.WIMM-4.1.15
kodi/usr/.../webinterface.default
	VIMM => kodi/addon/webinterface.WIMM-4.1.15
------------------------------------------------
New version : 
	webinterface.WIMM-4.1.15
	webinterface.WIMM-4.1.16
kodi/usr/.../webinterface.default
	VIMM => kodi/addon/webinterface.WIMM-4.1.15	(need a manual update)


I wasn't aware about " http://[ip address]/addons/ ", nice to know

Thanks
