### ISSUE TITLE
Cannot install WIMM in Isengard Nightlies

### ISSUE THREAD

**Issue by bolter1** [slash2009/XWMM#131]
Cannot install WIMM addon on any nightly version of Isengard. Last time I tries was with Isengard nightly 15.0-ALPHA2 Git:20150330-e826779 and WIMM version 4.1.18 I have tried the last 4 versions of WIMM along with the last 8 nightly versions of Isengard and always get the same error message "not correct structure"
Attached is link to log file - http://pastebin.com/G3CBY3W8

I am able to install all versions of WIMM into Helix 14.0 , 14.1 and 14.2 final, no worries. Just cannot install into Isengard

**Comment by uNiversaI** [comment]
@bolter1 please test https://github.com/uNiversaI/WIMM/releases/download/4.1.19/webinterface.WIMM-4.1.19.zip Ive installed it ok in isengard.

We need to address this in addon.xml so that both Helix and isengard can both be working ok cause, current releases only fully working in Helix.

**Comment by fyfe** [comment]
Isengard renames the web interface add-on extension from xbmc.gui.webinterface to xbmc.webinterface. It looks like the start of some major changes to Kodi's web interface addons.

I'm going to stick with my policy on supporting development/alpha releases of Kodi... I don't, they're to much of a moving target. The scripts that currently maintain the add-on repository for WIMM are very basic and to create separate builds for Isengard to remove 4 characters from a metadata file is a lot of work for very little benefit.

However I know people like to live on the bleeding edge so I will manually create an Isengard version which will be hosted at http://kodi.neptune-one.net/isengard/ these will not receive automatic updates.

I have begun work on a re-write of WIMM using a modern web framework however my free time is scarce at the moment so progress is very slow.

**Comment by uNiversaI** [comment]
again next month already beta1 of isengard.

**Comment by bolter1** [comment]
Thanks for all your hard work. All working brilliantly.
