### ISSUE TITLE
[Request] WIMM Standalone repository for multiple kodi version releases 

### ISSUE THREAD

**Issue by uNiversaI** [slash2009/XWMM#133]
Having repository being provided in addon, is practical but will become a messy hack, and more confusing to maintain both repo and addon imo.

This is based on https://github.com/xbmc/xbmc/blob/master/addons/repository.xbmc.org/addon.xml

Only thing that needs handling is the ***isengard*** directory portions and provide releases compatible with isengard new ```<extension point="xbmc.webinterface"/>```

Im unsure how @fyfe wants to handle two repos or however needed to make sure it works when releases for addon are made. Somewhat beyond my ability.

This is how it would look.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="repository.wimm.web"
       name="Official WIMM repository"
       version="1.0.0"
       provider-name="fyfe">
  <requires>
    <import addon="xbmc.addon" version="14.0.0"/>
  </requires>
    <extension point="xbmc.addon.repository"
	   name="Official WIMM Add-on Repository">
       <dir minversion="14.0.0">
            <info compressed="true">http://kodi.neptune-one.net/addons/addons.xml</info>
            <checksum>http://kodi.neptune-one.net/addons/addons.xml.md5</checksum>
            <datadir zip="true">http://kodi.neptune-one.net/addons</datadir>
            <hashes>true</hashes>
       </dir>
       <dir minversion="14.9.0">
            <info compressed="true">http://kodi.neptune-one.net/addons/isengard/addons.xml</info>
            <checksum>http://kodi.neptune-one.net/addons/isengard/addons.xml.md5</checksum>
            <datadir zip="true">http://kodi.neptune-one.net/addons/isengard</datadir>
            <hashes>true</hashes>
       </dir>
    </extension>
    <extension point="xbmc.addon.metadata">
        <summary lang="en">Official repository for WIMM web interface</summary>
        <description lang="en">WIMM repository providing WIMM web interface add-on for kodi</description>
        <disclaimer lang="en">This is a beta add-on repository</disclaimer>
        <platform>all</platform>
    </extension>
</addon>
```
Test zip for repo https://github.com/uNiversaI/WIMM/releases/download/1.0.0/repository.wimm.web-1.0.0.zip

This should work for existing Helix addon, not yet for isengard..

Please @fyfe handle the isengard directories on repo server and whatever else required there as Im unable to access this.

**Comment by uNiversaI** [comment]
@ fyfe WORK on this front https://github.com/slash2009/XWMM/pull/136

**Comment by fyfe** [comment]
I appreciate the work @uNiversaI.

Ok here's what I've done so far:
- Split the repository hosted at [kodi.neptune-one.net](http://kodi.neptune-one.net/addons) into separate repositories for helix and isengard
- Created a repository add-on ([repository.wimm.web](https://github.com/fyfe/repository.wimm.web)) removing the repository stuff from WIMM's addon.xml
- Created a new release of WIMM and added it to the new repositories (I haven't pushed this to github yet).

Now for the testing:
- Uninstall WIMM
- **HELIX** users install [repository.wimm.web](http://kodi.neptune-one.net/addons/helix/repository.wimm.web/repository.wimm.web-1.0.0.zip)
- **ISENGARD** users install [repository.wimm.web](http://kodi.neptune-one.net/addons/isengard/repository.wimm.web/repository.wimm.web-1.0.0.zip)
- Then from the add-on menu **in Kodi** select the WIMM repository and install WIMM

This will install the correct version for which ever version of Kodi you are running and provide automatic updates.

It'll be next week before I've got access to a machine running Kodi so if people can test this on Helix and Isengard it would be appreciated.

At the moment my script that automatically updates the repository when a release is tagged doesn't work with this new layout, I'm working on an updated one hopefully I'll get it done this weekend.

**Comment by uNiversaI** [comment]
why do you need a repo for each, the repo I done does all, no?

**Comment by fyfe** [comment]
Oops that was me typing without engaging my brain. You're right there is only one version of the repository add-on it's just included in both repositories. I've adjusted the instructions.

**Comment by uNiversaI** [comment]
read my post again. updated

**Comment by uNiversaI** [comment]
note I need to redo #136 PR because I realised I can create an empty branch with 

git checkout --orphan repository.wimm.web

**Comment by uNiversaI** [comment]
@fyfe 

Right see https://github.com/slash2009/XWMM/tree/repository.wimm.web and https://github.com/slash2009/XWMM/releases/tag/v.1.0.0

That should address part of my comments and keeps it all in one development roof.

Todo list for @fyfe

- [ ] review #132 and merge asap. 
- [ ] consider using some generic directory names for repo paths instead of specific helix/isengard (future proofing K.I.S.S.
- [ ] repository.wimm.web, available on server in own path, doesn't need helix/isengard repos.
- [ ] update server files K.I.S.S
- [ ] addon.xml extension points for isengard and own branch? <- no idea here.

**Comment by fyfe** [comment]
See [this comment](https://github.com/slash2009/XWMM/issues/131#issuecomment-89433748)

There's going to be more breaking changes to web interface add-ons in Kodi before Isengard is released. Until it hits beta (maybe alpha) release state I'm not going to play catch up.

**Comment by uNiversaI** [comment]
next month beta
